config/routes.rb
Rails.application.routes.draw do

  


  get '/nasaindex', to: 'nasa_picture#index'

  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help' 
  #/signup page is rooted the new action in users controller
  get  '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #Open Source
    get '/issdata', to: 'iss_map#index'

  resources :users
  resources :account_activations
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  
  def about
  end
  

  def help
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>NASA App</h1>
<p>
   This is the place where you can follow the location of the International Space Station <br>
   Go ahead and check if it flyes above your city! </p>
  <br><br><br><br><br><br><br><br><br><br><br><br><br>
 <h3> Created by Alex Donchev,   Stuart Melville,   Konstantin Milchev</h3>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
     <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost feed</h3>
      <div class="shado">
     <%= render 'shared/feed' %>
     </div>
    </div>
  </div>
<% else %>


<div class="center_jumbotron">
  <h1>Welcome to the NASA App</h1>

 


<p> This is the place where you can follow the location of the International Space Station <br>
Go ahead and check if it flyes above your city!</p>

 <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

 <%#= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %> 



<%#=  image_tag("kitten.jpg", alt: "Funny kitty") %>
  <br><br><br>
  <div class="container">
  	<div class="row">
  		<div class="col-md-4">
  			<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
  			<h3><%= link_to "User Friendly Interface", root_path %></h3>
  		</div>
  		<div class="col-md-4">
  			<span class="glyphicon glyphicon glyphicon-picture" aria-hidden="true"></span>
  			<h3><%= link_to "Nasa Photo of the Day", nasaindex_path %></h3>
  		</div>
  		<div class="col-md-4">
  			<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
  			<h3><%= link_to "Where is ISS", issdata_path %></h3>
  		</div>
  	</div>
  </div>
  <%end%>
</div>